const heroes = [
    {
        name: "Warden",
        faction: "Knights",
        gender: "Both",
        type: "Vanguard",
        release: "2017",
    },
    {
        name: "Peacekeeper",
        faction: "Knights",
        gender: "Female",
        type: "Assassin",
        release: "2017",
    },
    {
        name : "Centurion",
        faction: "Knights",
        gender: "Male",
        type: "Hybrid",
        release: "2017",
    },
    {
        name: "Conqueror",
        faction: "Knights",
        gender: "Male",
        type: "Heavy",
        release: "2017",
    },
    {
        name: "Lawbringer",
        faction: "Knights",
        gender: "Male",
        type: "Hybrid",
        release: "2017",
    },
    {
        name: "Gladiator",
        faction: "Knights",
        gender: "Female",
        type: "Assassin",
        release: "2017",
    },
    {
        name: "Black Prior",
        faction: "Knights",
        Gender: "Both",
        type: "Heavy",
        release: "2019",
    },
    {
        name: "Warmonger",
        faction: "Knights",
        gender: "Female",
        type: "Vanguard",
        release: "2020",
    },
    {
        name: "Gryphon",
        faction: "Knights",
        gender: "Male",
        type: "Heavy",
        release: "2020",
    },
    {
        name: "Raider",
        faction: "Vikings",
        gender: "Both",
        type: "Vanguard",
        release: "2017",
    },
    {
        name: "Warlord",
        faction: "Vikings",
        gender: "Male",
        type: "Heavy",
        release: "2017",
    },
    {
        name: "Berserker",
        faction: "Vikings",
        gender: "Both",
        type: "Assassin",
        release: "2017",
    },
    {
        name: "Valkyrie",
        faction: "Vikings",
        gender: "Female",
        type: "Hybrid",
        release: "2017",
    },
    {
        name: "Highlander",
        faction: "Vikings",
        gender: "Male",
        type: "Hybrid",
        release: "2017",
    },
    {
        name: "Shaman",
        faction: "Vikings",
        gender: "Female",
        type: "Assassin",
        release: "2017",
    },
    {
        name: "Jormungandr",
        faction: "Vikings",
        gender: "Both",
        type: "Heavy",
        release: "2019",
    },
    {
        name: "Varangian Guard",
        faction: "Vikings",
        gender: "Female",
        type: "Heavy",
        release: "2024",
    },
    {
        name: "Kensei",
        faction: "Samurai",
        gender: "Both",
        type: "Vanguard",
        release: "2017",
    },
    {
        name: "Shugoki",
        faction: "Samurai",
        gender: "Male",
        type: "Heavy",
        release: "2017",
    },
    {
        name: "Orochi",
        faction: "Samurai",
        gender: "Both",
        type: "Assassin",
        release: "2017",
    },
    {
        name: "Nobushi",
        faction: "Samurai",
        gender: "Female",
        type: "Hybrid",
        release: "2017",
    },
    {
        name: "Shinobi",
        faction: "Samurai",
        gender: "Both",
        type: "Assassin",
        release: "2017",
    },
    {
        name: "Aramusha",
        faction: "Samurai",
        gender: "Male",
        type: "Hybrid",
        release: "2017",
    },
    {
        name: "Hitokiri",
        faction: "Samurai",
        gender: "Both",
        type: "Heavy",
        release: "2019",
    },
    {
        name: "Kyoshin",
        faction: "Samurai",
        gender: "Male",
        type: "Hybrid",
        release: "2021",
    },
    {
        name: "Sohei",
        faction: "Samurai",
        gender: "Male",
        type: "Heavy",
        release: "2024",
    },
    {
        name: "Tiandi",
        faction: "Wu Lin",
        gender: "Both",
        type: "Vanguard",
        release: "2017",
    },
    {
        name: "Jiang Jun",
        faction: "Wu Lin",
        gender: "Male",
        type: "Heavy",
        release: "2018",
    },
    {
        name: "Nuxia",
        faction: "Wu Lin",
        gender: "Female",
        type: "Assassin",
        release: "2018",
    },
    {
        name: "Shaolin",
        faction: "Wu Lin",
        gender: "Male",
        type: "Hybrid",
        release: "2018",
    },
    {
        name: "Zhanhu",
        faction: "Wu Lin",
        gender: "Male",
        type: "Hybrid",
        release: "2019",
    },
    {
        name: "Juren",
        faction: "Wu Lin",
        gender: "Male",
        type: "Heavy",
        release: "2026",
    },
    {
        name: "Pirate",
        faction: "Outlanders",
        gender: "Female",
        type: "Hybrid",
        release: "2022",
    },
    {
        name: "Medjay",
        faction: "Outlanders",
        gender: "Male",
        type: "Hybrid",
        release: "2022",
    },
    {
        name: "Afeera",
        faction: "Outlanders",
        gender: "Female",
        type: "Hybrid",
        release: "2023",
    },
    {
        name: "Ocelotl",
        faction: "Outlanders",
        gender: "Male",
        type: "Hybrid",
        release: "2023",
    },
    {
        name: "Khatun",
        faction: "Outlanders",
        gender: "Female",
        type: "Assassin",
        release: "2025",
    },
    {
        name: "Virtuosa",
        faction: "Outlanders",
        gender: "Female",
        type: "Hybrid",
        release: "2025",
    }
]